// <auto-generated />
namespace FilmKiralamaSistm.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tabloguncelle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabloguncelle));
        
        string IMigrationMetadata.Id
        {
            get { return "202201271838257_tabloguncelle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
